apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pub.fullname" . }}
  labels:
    {{- include "pub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pub.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [
            "/nats-pub",
            "-s", "{{ .Values.args.natsEndpoint }}",
            "-d", "{{ .Values.args.delay }}",
            "-c", "{{ .Values.args.clusterName }}",
            "{{ .Values.args.subject }}",
          ]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
