apiVersion: v1
kind: Service
metadata:
  name: {{ include "nats.fullname" . }}
  labels:
    app: {{ include "nats.fullname" . }}
    {{- include "nats.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort }}
      targetPort: 4222
      name: client
    - port: {{ .Values.service.port }}
      targetPort: 8222
      name: monitor
  selector:
    app: {{ include "nats.fullname" . }}
