apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: stan-scaledobject
  labels:
    deploymentName: nats-sub
spec:
  pollingInterval: 10  # Optional. Default: 30 seconds
  cooldownPeriod: 30   # Optional. Default: 300 seconds
  minReplicaCount: 0   # Optional. Default: 0
  maxReplicaCount: 3   # Optional. Default: 100
  scaleTargetRef:
    deploymentName: nats-sub
  triggers:
    - type: stan
      metadata:
        natsServerMonitoringEndpoint: "my-nats:8222"
        queueGroup: "demo-group"
        durableName: "ImDurable"
        subject: "demo-test"
        lagThreshold: "1"